### ISSUE TITLE
how do i create a wordlist that only have 2 numbers and the rest are lowercase alphabet and it's length should be 8 ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [danielyc/hashcat-mask-generator#2]
just like this 1d5ghlbz

**Comment by danielyc** [comment]
this tool is not used for that purpose. You can just use the following mask. ?d?l?d?l?l?l?l?l

**Comment by minanagehsalalma** [comment]
> the following mask. ?d?l?d?l?l?l?l?l

@danielyc so it makes a list of only 2 digits and the reset are letters? (With the numbers in more than the first and third part of the password but still with no more than 2 digits just like this g7k8uolp - kpzg6vb9 )

If so how can i convert it to a wordlist?
